// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ciWp07_Kz4yBY03wK0X-oGxgMCJ83uw',
    appId: '1:458060208607:web:795c762a94fcfec0168c6a',
    messagingSenderId: '458060208607',
    projectId: 'employeemanagement-38629',
    authDomain: 'employeemanagement-38629.firebaseapp.com',
    storageBucket: 'employeemanagement-38629.firebasestorage.app',
    measurementId: 'G-FD3597Q0CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPuUuyeo8vq54zpd4UP6kA5G2Xk02907M',
    appId: '1:458060208607:android:cfe2faace2104cef168c6a',
    messagingSenderId: '458060208607',
    projectId: 'employeemanagement-38629',
    storageBucket: 'employeemanagement-38629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdSk9IkoB7pzDTNZY3Rkcf4w8q-lWIFN0',
    appId: '1:458060208607:ios:2e39a442acae2994168c6a',
    messagingSenderId: '458060208607',
    projectId: 'employeemanagement-38629',
    storageBucket: 'employeemanagement-38629.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementTask',
  );
}
